/**
 * Rollup Configuration
 *
 * Bundles modular source code into injectable IIFE for Chrome extension.
 * Output goes to /lib for the extension to use.
 */

import terser from '@rollup/plugin-terser';

const isProduction = process.env.BUILD === 'production';

export default [
  // Main validator - the big one
  {
    input: 'src/main.js',
    output: {
      file: 'lib/lms-qa-validator.js',
      format: 'iife',
      name: 'LMS_QA_VALIDATOR',
      banner: `/**
 * LMS QA Validator v${process.env.npm_package_version || '6.1.0'}
 * Built: ${new Date().toISOString()}
 *
 * Modular source in /src - DO NOT EDIT THIS FILE DIRECTLY
 * Run 'npm run build' to regenerate from source modules.
 */`,
      sourcemap: !isProduction
    },
    plugins: [
      isProduction && terser({
        format: {
          comments: /^!/  // Keep banner comment
        }
      })
    ].filter(Boolean)
  },

  // Tasks extractor - network interceptor
  {
    input: 'src/tasks-extractor/main.js',
    output: {
      file: 'lib/tasks-extractor.js',
      format: 'iife',
      name: 'LMS_QA_TASKS',
      banner: `/**
 * LMS QA Tasks Extractor
 * Built: ${new Date().toISOString()}
 */`,
      sourcemap: !isProduction
    },
    plugins: [
      isProduction && terser({
        format: {
          comments: /^!/
        }
      })
    ].filter(Boolean)
  }
];
